import AboutMeSection from '@/components/aboutMeSection'
import ProyectsSection from '@/components/proyectsSection'
import Statistics from '@/components/statistics'
import Head from 'next/head'
import Image from 'next/image'
import { getPlaiceholder } from 'plaiceholder'
import { useState } from 'react'

export default function Home({ imageProps }) {
  const [isLoading, setLoading] = useState(true)

  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="grid grid-cols-1 md:grid-cols-[43%_auto] content-center place-content-center gap-5">
        <header>
          <Image
            alt="profile"
            width={8000}
            height={8000}
            quality={100}
            {...imageProps}
            placeholder="blur"
            className={`
               md:rounded-lg h-64 md:h-full duration-700 ease-in-out group-hover:opacity-75 
              ${isLoading ? 'blur-lg grayscale opacity-20 ' : 'blur-0'})`}
            onLoadingComplete={() => setLoading(false)}
            style={{
              width: '100%',
              objectFit: 'cover',
            }}
          />
        </header>

        <div className="flex flex-col justify-between gap-12   py-2 md:p-0 px-6 md:mt-6">
          <AboutMeSection />
          <Statistics />
          <ProyectsSection />
        </div>
      </div>
    </>
  )
}

export const getStaticProps = async () => {
  const { base64, img } = await getPlaiceholder('/images/profile.jpeg')

  return {
    props: {
      imageProps: {
        ...img,
        blurDataURL: base64,
      },
    },
  }
}
