name: Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm i
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Build app
        run: |
          touch .env.production
          echo ENV_GITHUBTOKEN=${{ secrets.ENV_GITHUBTOKEN }} >> .env.production 
          echo ENV_TOKEN_API=${{ secrets.ENV_TOKEN_API }} >> .env.production 
          echo NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }} >> .env.production 
          echo ENV_TOKEN_NOTION=${{ secrets.ENV_TOKEN_NOTION }} >> .env.production 
          npm run build
      - name: Run Playwright tests
        run: npx playwright test
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
